"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc.aio as grpc
import typing
from . import hello_pb2 as hello_pb2

class HelloStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    SayHello: grpc.UnaryUnaryMultiCallable[
        hello_pb2.HelloRequest,
        hello_pb2.HelloReply,
    ]

class HelloServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def SayHello(
        self,
        request: hello_pb2.HelloRequest,
        context: grpc.ServicerContext[typing.Any, typing.Any],
    ) -> hello_pb2.HelloReply: ...

def add_HelloServicer_to_server(
    servicer: HelloServicer, server: grpc.Server
) -> None: ...
